apiVersion: apps/v1
kind: Deployment
metadata:
  name: classify-patient-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classify-patient-microservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: classify-patient-microservice
    spec:
      containers:
        - name: classify-patient-microservice-image
          image: us-central1-docker.pkg.dev/tt-covid19-patients/classify-patient-microservice-repository/classify-patient-microservice-image:latest
          imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always