apiVersion: apps/v1
kind: Deployment
metadata:
  name: classify-patient-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classify-patient-microservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: classify-patient-microservice
    spec:
      containers:
        - name: classify-patient-microservice-container
          image: us-central1-docker.pkg.dev/covid19-patients-tt/classify-patient-microservice-repository/classify-patient-microservice-image:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_DEPLOYMENT_URL
              valueFrom:
                secretKeyRef:
                  name: classify-patient-microservice-secrets
                  key: DATABASE_DEPLOYMENT_URL
                  optional: false

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: classify-patient-microservice-secrets
                  key: DATABASE_NAME
                  optional: false

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: classify-patient-microservice-secrets
                  key: SECRET_KEY
                  optional: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always