apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
environment: production
metadata:
  name: ${{secrets.GKE_DEPLOYMENT_NAME}}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${{secrets.GKE_DEPLOYMENT_NAME}}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85