apiVersion: v1
kind: Service
metadata:
  name: classify-patient-microservice
  labels:
    app: classify-patient-microservice
spec:
  type: LoadBalancer
  selector:
    app: classify-patient-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080