
name: Deploy to Google Kubernetes Engine
on:
  pull_request:
    types: [closed]
    branches:
      - "main"
jobs:
  setup-build-build-deploy:
    name: Deploy to Google Kubernetes Engine
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE_LOCATION: ${{secrets.GAR_REPOSITORY_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{secrets.GAR_REPOSITORY_NAME}}/${{secrets.DOCKER_IMAGE}}

    if: github.event.pull_request.merged
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIALS}}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get GKE Credentials
      run: |-
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone=${{secrets.GKE_CLUSTER_ZONE}} --project=${{secrets.GCP_PROJECT_ID}}

    - name: Build Docker image
      run: |-
        gcloud auth configure-docker ${{secrets.GAR_REPOSITORY_REGION}}-docker.pkg.dev
        docker build -t ${{secrets.DOCKER_IMAGE}} .
        docker tag ${{secrets.DOCKER_IMAGE}} ${{env.DOCKER_IMAGE_LOCATION}}:latest

    - name: Push the Docker image to Google Artifact Registry
      run: |-
        docker push ${{env.DOCKER_IMAGE_LOCATION}}:latest     

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy the Docker image to the GKE cluster
      run: |-
        ./kustomize edit set image ${{env.DOCKER_IMAGE_LOCATION}}:latest
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/${{secrets.GKE_DEPLOYMENT_NAME}}
        kubectl get services -o wide
