name: Run Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Testing dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s app/infrastructure/adapters/input/flask/tests -p "*_test.py"